apiVersion: v1
data:
  EMOJISVC_HOST: emoji-tidlor.odde-poc:8081
  INDEX_BUNDLE: dist/index_bundle.js
  VOTINGSVC_HOST: emojivoto-voting:8082
  WEB_PORT: "8080"
kind: ConfigMap
metadata:
  name: emojivoto-web
